In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
a.dtype

dtype('int32')

In [5]:
a = np.array([1, 2, '3', True])
a

array(['1', '2', '3', 'True'], dtype='<U11')

In [7]:
a[0]

'1'

In [8]:
a[1]

'2'

In [9]:
a[1] = 123
a

array(['1', '123', '3', 'True'], dtype='<U11')

In [10]:
a[1] = 234
a

array(['1', '234', '3', 'True'], dtype='<U11')

In [25]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[2]

3

In [26]:
a[[1,1,1,1,1,1,]]

array([2, 2, 2, 2, 2, 2])

In [27]:
a[[1,1,1]]

array([2, 2, 2])

In [28]:
a[[True, False, False, True, True, False, False, False, True]]

array([1, 4, 5, 9])

In [29]:
b = a.reshape((3, 3))

In [24]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
b[1][2]

6

In [32]:
b[1, 2]

6