In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 10, 20 ,30])

In [4]:
a

array([ 1,  2,  3, 10, 20, 30])

In [5]:
a.sum()

66

In [16]:
np.sum(a)

66

In [14]:
a.mean()

11.0

In [15]:
np.mean(a)

11.0

In [18]:
a.max()

30

In [19]:
np.max(a)

30

In [20]:
a.min()

1

In [21]:
np.min(a)

1

In [22]:
a.resize(3, 2)

In [23]:
a

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [24]:
a.sum()

66

In [25]:
a.sum(axis=0)

array([24, 42])

In [26]:
a.sum(axis=1)

array([ 3, 13, 50])

In [27]:
a.max(axis=0)

array([20, 30])

In [28]:
a.max(axis=1)

array([ 2, 10, 30])

In [34]:
a = np.array([1, 1, 5, -44, 32, 21])

In [35]:
a

array([  1,   1,   5, -44,  32,  21])

In [36]:
np.abs(a)

array([ 1,  1,  5, 44, 32, 21])

In [37]:
np.abs(-10.5)

10.5

In [39]:
np.abs([-10.5, 2])

array([10.5,  2. ])

In [40]:
a

array([  1,   1,   5, -44,  32,  21])

In [41]:
np.amax(a)

32

In [42]:
a.max()

32

In [43]:
a.amax()

AttributeError: 'numpy.ndarray' object has no attribute 'amax'

In [44]:
np.amin(a)

-44

In [45]:
np.around(0.7)

1.0

In [46]:
np.around(0.5)

0.0

In [47]:
a

array([  1,   1,   5, -44,  32,  21])

In [48]:
np.around(a)

array([  1,   1,   5, -44,  32,  21])

In [49]:
np.argmax(a)

4

In [50]:
np.argmin(a)

3

In [57]:
a.resize(2, 3)

In [58]:
a

array([[  1,   1,   5],
       [-44,  32,  21]])

In [59]:
np.amax(a)

32

In [63]:
np.amax(a, axis=0)

array([ 1, 32, 21])

In [69]:
np.amax(a, axis=1)

array([ 5, 32])

In [70]:
a = np.linspace(0, np.pi, 10)

In [71]:
a

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [72]:
np.sin(a)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

In [73]:
np.cos(a)

array([ 1.        ,  0.93969262,  0.76604444,  0.5       ,  0.17364818,
       -0.17364818, -0.5       , -0.76604444, -0.93969262, -1.        ])

In [75]:
np.cos([0, 1.57, 3.14])

array([ 1.00000000e+00,  7.96326711e-04, -9.99998732e-01])

In [78]:
np.random.rand()

0.39151961954134185

In [79]:
np.random.rand()

0.08099802509737097

In [80]:
np.random.rand()

0.7240486392793297

In [81]:
np.random.rand(5)

array([0.09889241, 0.96445991, 0.22543118, 0.523448  , 0.72056913])

In [82]:
np.random.rand(2, 3)

array([[0.46365416, 0.39971846, 0.12546841],
       [0.89186563, 0.30735732, 0.12562249]])

In [93]:
np.random.randint(10)

7

In [94]:
np.random.randint(10)

9

In [95]:
np.random.randint(10)

1

In [100]:
np.random.randint(5, 10)

9

In [101]:
np.random.randint(5, 10)

5

In [102]:
np.random.randint(5, 10)

6

In [103]:
np.random.randint(5, 10)

6

In [105]:
np.random.randint(5, size=4)

array([4, 4, 0, 3])

In [113]:
np.random.randint(1, 10, size = (2, 5))

array([[9, 3, 5, 2, 2],
       [3, 6, 3, 9, 9]])

In [115]:
np.random.randint(5, 16, size = (2, 11))

array([[11,  8, 14,  5, 15, 11, 12, 12, 14,  7,  6],
       [12, 10, 15, 11, 15, 14, 13, 13, 12, 14, 11]])

In [119]:
np.random.randn()

-3.1431134587699447

In [120]:
np.random.randn()

0.18404229859178345

In [121]:
np.random.randn()

2.1406837694566643

In [122]:
np.random.randn()

0.5355439888285277

In [123]:
np.random.randn(5)

array([-0.88868023,  1.17227685,  1.18974926,  0.73138915,  0.46752344])

In [124]:
np.random.randn(2, 3)

array([[-0.81059107, -0.57286919,  0.29901184],
       [ 0.40501016,  0.20165525, -0.87166286]])

In [125]:
np.random.pareto(2, size=3)

array([2.40856475, 0.5334372 , 0.56897924])

In [126]:
np.random.pareto(2.0, size=3)

array([0.73191048, 0.1878775 , 0.0249211 ])

In [128]:
np.random.beta(0.1, 0.3, size=(3,3))

array([[4.61476276e-01, 1.57606136e-02, 9.95947315e-01],
       [1.52093997e-06, 2.60543649e-07, 7.67633289e-01],
       [5.07086142e-01, 1.89447096e-08, 6.78897893e-03]])

In [129]:
np.random.randn()

0.7407182878489309

In [130]:
np.random.randn()

1.0109350528197252

In [131]:
np.random.randn()

-1.436315107783596

In [132]:
np.random.seed(13)

In [133]:
np.random.randn()

-0.712390662050588

In [143]:
np.random.randn()

0.753766378659703

In [144]:
np.random.seed(13)

In [145]:
np.random.randn()

-0.712390662050588

In [158]:
np.random.seed(13)

In [159]:
np.random.randint(10, size=10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])

In [160]:
np.random.seed(13)

In [161]:
np.random.randint(10, size=10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])

In [162]:
np.random.randint(10, size=10)

array([6, 5, 9, 4, 2, 0, 3, 5, 3, 6])

In [163]:
np.random.seed(13)

In [164]:
np.random.randint(10, size=10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])

In [165]:
np.random.seed(10)

In [166]:
np.random.randint(10, size=10)

array([9, 4, 0, 1, 9, 0, 1, 8, 9, 0])

In [167]:
np.random.seed(10)

In [168]:
np.random.randint(10, size=10)

array([9, 4, 0, 1, 9, 0, 1, 8, 9, 0])

In [169]:
a = np.arange(10)

In [170]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
np.random.shuffle(a)

In [178]:
a

array([0, 1, 5, 8, 9, 4, 7, 6, 3, 2])

In [242]:
a = np.arange(1, 10).reshape(3, 3)

In [243]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [244]:
np.random.shuffle(a)

In [245]:
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [246]:
np.random.permutation(10)

array([1, 6, 3, 5, 9, 2, 8, 0, 7, 4])

In [255]:
np.random.permutation(a)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [4]:
a = np.arange(1,10).reshape(3, 3)

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
g = []

In [10]:
for i in a:
    g.append(np.random.permutation(i))

In [11]:
np.array(g)

array([[3, 1, 2],
       [6, 5, 4],
       [7, 9, 8]])

In [267]:
x = np.array([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])

In [268]:
y = np.array([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])

In [269]:
x

array([ 1,  4,  3,  7, 10,  8, 14, 21, 20, 23])

In [270]:
y

array([ 4,  1,  6,  9, 13, 11, 16, 19, 15, 22])

In [272]:
np.median(x) # x dəyərlərinin medianının hesablanması

9.0

In [274]:
np.var(x) # dispersiyasını hesablamaq

57.29

In [276]:
np.std(x) # standart kənarlaşmasını hesablamaq

7.569015788066504

In [282]:
xy = np.vstack((x, y))

In [283]:
xy

array([[ 1,  4,  3,  7, 10,  8, 14, 21, 20, 23],
       [ 4,  1,  6,  9, 13, 11, 16, 19, 15, 22]])

In [286]:
np.corrcoef(xy)

array([[1.        , 0.93158099],
       [0.93158099, 1.        ]])

In [287]:
np.cov(xy)

array([[63.65555556, 49.82222222],
       [49.82222222, 44.93333333]])

In [291]:
np.correlate(x, y)

array([1736])