In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4], 'float64')

In [5]:
a

array([1., 2., 3., 4.])

In [6]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.intc,
 5: numpy.intc,
 'uint': numpy.uint32,
 'I': numpy.uintc,
 6: numpy.uintc,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'ulong': numpy.uint32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex128,
 'F': numpy.complex

In [7]:
a = np.array([1, 2, 3, 4], 'uintc')

In [8]:
a

array([1, 2, 3, 4], dtype=uint32)

In [9]:
a = np.array([1, 2, 3, 4], 'str_')

In [10]:
a

array(['1', '2', '3', '4'], dtype='<U1')

In [11]:
np.complex64(10)

(10+0j)

In [13]:
np.int16(10.5)

10

In [14]:
a = np.array([1, 2, 500, 1000], dtype = 'int8')

In [15]:
a

array([  1,   2, -12, -24], dtype=int8)

In [16]:
a = np.array([1, 2, 500, 1000])

In [19]:
a

array([   1,    2,  500, 1000])

In [20]:
np.complex64(a)

array([   1.+0.j,    2.+0.j,  500.+0.j, 1000.+0.j], dtype=complex64)

In [21]:
a

array([   1,    2,  500, 1000])

In [22]:
b = np.complex64(a)

In [23]:
b

array([   1.+0.j,    2.+0.j,  500.+0.j, 1000.+0.j], dtype=complex64)

In [24]:
c = np.int32(b)

C:\Users\dell\AppData\Local\Temp\ipykernel_7456\4084964917.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  c = np.int32(b)


In [25]:
c

array([   1,    2,  500, 1000])

In [28]:
np.array((1, 2, 3))

array([1, 2, 3])

In [41]:
np.array("Hello")

array('Hello', dtype='<U5')

In [48]:
a = np.array([[1, 2], [3,4], [5, 6]])

In [49]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
a = np.array([[1, 2], [3,4], [5, 6, 7]])

C:\Users\dell\AppData\Local\Temp\ipykernel_7456\2330150720.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1, 2], [3,4], [5, 6, 7]])


In [44]:
a

array([list([1, 2]), list([3, 4]), list([5, 6, 7])], dtype=object)

In [70]:
b = np.array([[[1, 2], [3, 5]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [71]:
b

array([[[ 1,  2],
        [ 3,  5]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [72]:
b[0]

array([[1, 2],
       [3, 5]])

In [73]:
b[1]

array([[5, 6],
       [7, 8]])

In [74]:
b[2]

array([[ 9, 10],
       [11, 12]])

In [75]:
b[0, 0]

array([1, 2])

In [76]:
b[0, 0, 0]

1