In [135]:
import numpy as np

In [136]:
np.array([1, 2, 3])

array([1, 2, 3])

In [137]:
np.array([0] * 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
np.array([1] * 15)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [139]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [141]:
np.empty(10, dtype = 'int16')

array([     0,      0,      0,      0, -22590,   8833,   6400, -32768,
            0,      0], dtype=int16)

In [142]:
np.empty((3, 2), dtype = 'int16')

array([[  7840, -11778],
       [    58,      0],
       [     0,      0]], dtype=int16)

In [143]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [144]:
np.eye(4, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [145]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [146]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [147]:
np.ones((4, 3), 'int8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [148]:
np.full((3, 2), -1)

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

In [149]:
np.mat('1 2 3 4')

matrix([[1, 2, 3, 4]])

In [150]:
np.mat('1, 2, 3, 4')

matrix([[1, 2, 3, 4]])

In [151]:
np.mat('1, 2; 3, 4')

matrix([[1, 2],
        [3, 4]])

In [152]:
np.mat([5, 4, 3])

matrix([[5, 4, 3]])

In [153]:
np.mat([(1, 2, 3), (4, 5, 6)])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [154]:
np.mat([(1, 2, 3), (4, 5, 6, 7)])

matrix([[(1, 2, 3), (4, 5, 6, 7)]], dtype=object)

In [155]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [156]:
np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

In [158]:
np.diagflat([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [159]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [160]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [161]:
np.tri(2, 4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.]])

In [162]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

In [163]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [171]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [189]:
np.tril([1, 2, 3])

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [190]:
np.tril([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

array([[[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]]])

In [191]:
np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 20, 30], [40, 50, 60], [70, 80, 90]], [[100, 200, 300], [400, 500, 600], [700, 800, 900]]])

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [192]:
np.tril([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 20, 30], [40, 50, 60], [70, 80, 90]], [[100, 200, 300], [400, 500, 600], [700, 800, 900]]])

array([[[  1,   0,   0],
        [  4,   5,   0],
        [  7,   8,   9]],

       [[ 10,   0,   0],
        [ 40,  50,   0],
        [ 70,  80,  90]],

       [[100,   0,   0],
        [400, 500,   0],
        [700, 800, 900]]])

In [193]:
np.vander([1, 2, 3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [238]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [239]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [240]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [242]:
np.arange(0, np.pi, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [243]:
np.cos(np.arange(0, np.pi, 0.1))

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [246]:
np.linspace(0, np.pi, 0)

array([], dtype=float64)

In [247]:
np.linspace(0, np.pi, 1)

array([0.])

In [251]:
np.linspace(0, np.pi, 2)

array([0.        , 3.14159265])

In [252]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

In [270]:
np.linspace(0, np.pi, 4)

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [271]:
np.linspace(0, np.pi, 5)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [272]:
np.linspace(4, 50, 5)

array([ 4. , 15.5, 27. , 38.5, 50. ])

In [323]:
np.logspace(0, 1, 3)

array([ 1.        ,  3.16227766, 10.        ])

In [285]:
import math

In [324]:
np.logspace(1, 6, 3)

array([1.00000000e+01, 3.16227766e+03, 1.00000000e+06])

In [325]:
math.floor(3.16227766e+03)

3162

In [326]:
np.logspace(0, 1, 4)

array([ 1.        ,  2.15443469,  4.64158883, 10.        ])

In [327]:
np.geomspace(1, 4, 3)

array([1., 2., 4.])

In [330]:
np.geomspace(1, 16, 5)

array([ 1.,  2.,  4.,  8., 16.])

In [336]:
np.geomspace(1, 16, 4)

array([ 1.        ,  2.5198421 ,  6.34960421, 16.        ])

In [340]:
a = np.array([(1, 2), (3, 4)])

In [341]:
a

array([[1, 2],
       [3, 4]])

In [342]:
b = np.copy(a)

In [343]:
b

array([[1, 2],
       [3, 4]])

In [344]:
b[0] = 100

In [345]:
b

array([[100, 100],
       [  3,   4]])

In [346]:
a

array([[1, 2],
       [3, 4]])

In [390]:
def getRange(x, y):
    return 100*x + y

In [391]:
a = np.fromfunction(getRange, (2, 2))

In [392]:
a

array([[  0.,   1.],
       [100., 101.]])

In [393]:
np.fromfunction(lambda x, y: 100 * x +y, (2, 2))

array([[  0.,   1.],
       [100., 101.]])

In [396]:
np.fromiter('hello', dtype = "U1")

array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

In [400]:
def getRange(N):
    for i in range(N):
        yield i

In [402]:
a = np.fromiter(getRange(4), dtype = 'int8')

In [403]:
a

array([0, 1, 2, 3], dtype=int8)

In [404]:
np.fromstring('1 2 3', dtype = 'int16', sep = ' ')

array([1, 2, 3], dtype=int16)

In [405]:
np.fromstring('1, 2, 3', dtype = 'int16', sep = ', ')

array([1, 2, 3], dtype=int16)