In [4]:
import numpy as np

In [5]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [6]:
a.dtype

dtype('float64')

In [7]:
a.dtype = np.int8()

In [8]:
a

array([-102, -103, -103, -103, -103, -103,  -71,   63, -102, -103, -103,
       -103, -103, -103,  -55,   63,   51,   51,   51,   51,   51,   51,
        -45,   63, -102, -103, -103, -103, -103, -103,  -39,   63,    0,
          0,    0,    0,    0,    0,  -32,   63,   51,   51,   51,   51,
         51,   51,  -29,   63,  102,  102,  102,  102,  102,  102,  -26,
         63, -102, -103, -103, -103, -103, -103,  -23,   63,  -51,  -52,
        -52,  -52,  -52,  -52,  -20,   63], dtype=int8)

In [9]:
a.dtype

dtype('int8')

In [10]:
a.size

72

In [11]:
a.dtype = np.float64()

In [12]:
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [13]:
a.dtype = 'float32'

In [14]:
a

array([-1.58818684e-23,  1.44999993e+00, -1.58818684e-23,  1.57499993e+00,
        4.17232506e-08,  1.64999998e+00, -1.58818684e-23,  1.69999993e+00,
        0.00000000e+00,  1.75000000e+00,  4.17232506e-08,  1.77499998e+00,
        2.72008302e+23,  1.79999995e+00, -1.58818684e-23,  1.82499993e+00,
       -1.07374184e+08,  1.84999990e+00], dtype=float32)

In [15]:
a.size

18

In [16]:
a.itemsize

4

In [17]:
a.dtype = 'float64'

In [18]:
a.itemsize

8

In [19]:
a.size * a.itemsize

72

In [20]:
b = np.ones((3, 4, 5))

In [21]:
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [22]:
b.ndim

3

In [23]:
b.shape

(3, 4, 5)

In [24]:
b.shape = 60

In [25]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
b.shape = 12, 5

In [27]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
c = b.reshape(3, 2, 10)

In [29]:
c

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [30]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
b[0, 0] = 10

In [32]:
b

array([[10.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [33]:
c

array([[[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

In [34]:
print(id(b), id(c))

948129299600 948079371696


In [35]:
d = b.T

In [36]:
d

array([[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [37]:
b

array([[10.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [38]:
b[0, 1] = 10

In [39]:
b

array([[10., 10.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [40]:
c

array([[[10., 10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

In [41]:
d

array([[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [73]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [74]:
b = a

In [75]:
a.shape = (3, 3)

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [104]:
b = a.view()

In [105]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a.shape = 3, 3

In [107]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
b = np.array(a)

In [137]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
a[0] = 100

In [139]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [140]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
c = a.copy()

In [142]:
c

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [143]:
c[0] = 1

In [144]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])