In [47]:
import numpy as np

In [48]:
a = np.arange(10)

In [49]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a.shape = 2, 5

In [51]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
b = a.reshape(10)

In [53]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
b[0] = -1

In [56]:
b

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [57]:
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [58]:
b = a.reshape(9)

ValueError: cannot reshape array of size 10 into shape (9,)

In [59]:
a.shape = 3, 3

ValueError: cannot reshape array of size 10 into shape (3,3)

In [60]:
a.shape = -1, 2

In [61]:
a

array([[-1,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [62]:
a.shape = -1, 5

In [63]:
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [64]:
b

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [65]:
b.reshape(-1, 1)

array([[-1],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [66]:
b

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [67]:
b.reshape(1, -1)

array([[-1,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [68]:
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [69]:
a.ravel()

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [70]:
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [71]:
c = a.ravel()

In [72]:
c

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [73]:
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [74]:
c[0] = 1

In [75]:
c

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
a.shape = -1

In [78]:
a

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a.reshape(2, 5)

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
a

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a.resize(2, 5)

In [82]:
a

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
a.resize(3, 3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [84]:
a.resize(3, 3, refcheck=False)

In [85]:
a

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
a.resize(4, 5, refcheck=False)

In [88]:
a

array([[1, 1, 2, 3, 4],
       [5, 6, 7, 8, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [108]:
a = np.array([(1, 2, 3), (1, 4, 9), (1, 8, 27)])

In [109]:
a

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [110]:
b = a.T

In [111]:
b

array([[ 1,  1,  1],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [112]:
b[0, 0] = 100

In [113]:
b

array([[100,   1,   1],
       [  2,   4,   8],
       [  3,   9,  27]])

In [114]:
a

array([[100,   2,   3],
       [  1,   4,   9],
       [  1,   8,  27]])

In [115]:
b[1, 0] = 100

In [116]:
b

array([[100,   1,   1],
       [100,   4,   8],
       [  3,   9,  27]])

In [117]:
a

array([[100, 100,   3],
       [  1,   4,   9],
       [  1,   8,  27]])

In [137]:
x = np.arange(1, 10)

In [138]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
x.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
x.shape = 1, -1

In [141]:
x

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [142]:
x.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [144]:
x = np.arange(1, 10)

In [145]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
x.shape = -1, 1

In [147]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [149]:
x_test = np.arange(32).reshape(8, 2, 2)

In [150]:
x_test

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [153]:
x_test.shape

(8, 2, 2)

In [155]:
x_test4 = np.expand_dims(x_test, axis=0)

In [156]:
x_test4.shape

(1, 8, 2, 2)

In [158]:
x_test4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]]])

In [159]:
x_test4[0, 0, 0, 0] = -100

In [160]:
x_test4

array([[[[-100,    1],
         [   2,    3]],

        [[   4,    5],
         [   6,    7]],

        [[   8,    9],
         [  10,   11]],

        [[  12,   13],
         [  14,   15]],

        [[  16,   17],
         [  18,   19]],

        [[  20,   21],
         [  22,   23]],

        [[  24,   25],
         [  26,   27]],

        [[  28,   29],
         [  30,   31]]]])

In [161]:
x_test

array([[[-100,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]],

       [[  12,   13],
        [  14,   15]],

       [[  16,   17],
        [  18,   19]],

       [[  20,   21],
        [  22,   23]],

       [[  24,   25],
        [  26,   27]],

       [[  28,   29],
        [  30,   31]]])

In [162]:
a = np.append(x_test4, x_test4, axis=0)

In [163]:
a.shape

(2, 8, 2, 2)

In [164]:
a

array([[[[-100,    1],
         [   2,    3]],

        [[   4,    5],
         [   6,    7]],

        [[   8,    9],
         [  10,   11]],

        [[  12,   13],
         [  14,   15]],

        [[  16,   17],
         [  18,   19]],

        [[  20,   21],
         [  22,   23]],

        [[  24,   25],
         [  26,   27]],

        [[  28,   29],
         [  30,   31]]],


       [[[-100,    1],
         [   2,    3]],

        [[   4,    5],
         [   6,    7]],

        [[   8,    9],
         [  10,   11]],

        [[  12,   13],
         [  14,   15]],

        [[  16,   17],
         [  18,   19]],

        [[  20,   21],
         [  22,   23]],

        [[  24,   25],
         [  26,   27]],

        [[  28,   29],
         [  30,   31]]]])

In [165]:
b = np.delete(a, 0, axis=0)

In [166]:
b.shape

(1, 8, 2, 2)

In [167]:
b

array([[[[-100,    1],
         [   2,    3]],

        [[   4,    5],
         [   6,    7]],

        [[   8,    9],
         [  10,   11]],

        [[  12,   13],
         [  14,   15]],

        [[  16,   17],
         [  18,   19]],

        [[  20,   21],
         [  22,   23]],

        [[  24,   25],
         [  26,   27]],

        [[  28,   29],
         [  30,   31]]]])

In [169]:
x_test4.shape

(1, 8, 2, 2)

In [170]:
x_test4

array([[[[-100,    1],
         [   2,    3]],

        [[   4,    5],
         [   6,    7]],

        [[   8,    9],
         [  10,   11]],

        [[  12,   13],
         [  14,   15]],

        [[  16,   17],
         [  18,   19]],

        [[  20,   21],
         [  22,   23]],

        [[  24,   25],
         [  26,   27]],

        [[  28,   29],
         [  30,   31]]]])

In [171]:
b = np.expand_dims(x_test4, axis = -1)

In [172]:
b.shape

(1, 8, 2, 2, 1)

In [173]:
b

array([[[[[-100],
          [   1]],

         [[   2],
          [   3]]],


        [[[   4],
          [   5]],

         [[   6],
          [   7]]],


        [[[   8],
          [   9]],

         [[  10],
          [  11]]],


        [[[  12],
          [  13]],

         [[  14],
          [  15]]],


        [[[  16],
          [  17]],

         [[  18],
          [  19]]],


        [[[  20],
          [  21]],

         [[  22],
          [  23]]],


        [[[  24],
          [  25]],

         [[  26],
          [  27]]],


        [[[  28],
          [  29]],

         [[  30],
          [  31]]]]])

In [174]:
c = np.squeeze(b)

In [175]:
c.shape

(8, 2, 2)

In [176]:
c

array([[[-100,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]],

       [[  12,   13],
        [  14,   15]],

       [[  16,   17],
        [  18,   19]],

       [[  20,   21],
        [  22,   23]],

       [[  24,   25],
        [  26,   27]],

       [[  28,   29],
        [  30,   31]]])

In [177]:
c = np.squeeze(b, axis=0)

In [179]:
c.shape

(8, 2, 2, 1)

In [180]:
c

array([[[[-100],
         [   1]],

        [[   2],
         [   3]]],


       [[[   4],
         [   5]],

        [[   6],
         [   7]]],


       [[[   8],
         [   9]],

        [[  10],
         [  11]]],


       [[[  12],
         [  13]],

        [[  14],
         [  15]]],


       [[[  16],
         [  17]],

        [[  18],
         [  19]]],


       [[[  20],
         [  21]],

        [[  22],
         [  23]]],


       [[[  24],
         [  25]],

        [[  26],
         [  27]]],


       [[[  28],
         [  29]],

        [[  30],
         [  31]]]])

In [181]:
c = np.squeeze(b, axis=1)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [229]:
a = np.arange(1, 10)

In [230]:
a.shape

(9,)

In [231]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
b = a[np.newaxis, :]

In [236]:
b.shape

(1, 9)

In [237]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [239]:
b = a[:, np.newaxis]

In [240]:
b.shape

(9, 1)

In [241]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [242]:
c = a[np.newaxis, :, np.newaxis]

In [243]:
c.shape

(1, 9, 1)

In [244]:
c

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])