In [23]:
import numpy as np

In [24]:
a = np.array([(1, 2), (3, 4)])

In [25]:
b = np.array([(5, 6), (7, 8)])

In [26]:
a

array([[1, 2],
       [3, 4]])

In [27]:
b

array([[5, 6],
       [7, 8]])

In [28]:
np.hstack([a, b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
np.vstack([b, a])

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [31]:
np.vstack([b, a, a])

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [32]:
a = np.array(range(18))

In [33]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [34]:
a = np.arange(18)

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [36]:
a = np.fromiter(range(18), dtype='int32')

In [37]:
b = np.fromiter(range(18, 36), dtype='int32')

In [38]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [39]:
b

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35])

In [40]:
a.resize(3, 3, 2)

In [41]:
b.resize(3, 3, 2)

In [42]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [43]:
b

array([[[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [44]:
c = np.hstack([a, b])

In [45]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [30, 31],
        [32, 33],
        [34, 35]]])

In [46]:
c.shape

(3, 6, 2)

In [47]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [48]:
b

array([[[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [49]:
d = np.vstack([a, b])

In [50]:
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [51]:
d.shape

(6, 3, 2)

In [52]:
a = np.fromstring('1 2 3 4', sep=' ')

In [53]:
b = np.fromstring('5 6 7 8', sep=' ')

In [54]:
a

array([1., 2., 3., 4.])

In [55]:
b

array([5., 6., 7., 8.])

In [56]:
np.hstack([a, b])

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [57]:
np.vstack([a, b])

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [58]:
np.column_stack([a, b])

array([[1., 5.],
       [2., 6.],
       [3., 7.],
       [4., 8.]])

In [59]:
np.row_stack([a, b])

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [157]:
a = np.arange(1, 19)

In [158]:
b = np.arange(19, 37)

In [159]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [160]:
b

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36])

In [161]:
a.resize(3, 3, 2)

In [162]:
b.resize(3, 3, 2)

In [163]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [164]:
b

array([[[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36]]])

In [165]:
c0 = np.concatenate([a, b], axis=0)

In [166]:
c0.shape

(6, 3, 2)

In [167]:
c0

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36]]])

In [168]:
c1 = np.concatenate([a, b], axis=1)

In [169]:
c1.shape

(3, 6, 2)

In [170]:
c1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [31, 32],
        [33, 34],
        [35, 36]]])

In [171]:
c3 = np.concatenate([a, b], axis=2)

In [172]:
c3.shape

(3, 3, 4)

In [173]:
c3

array([[[ 1,  2, 19, 20],
        [ 3,  4, 21, 22],
        [ 5,  6, 23, 24]],

       [[ 7,  8, 25, 26],
        [ 9, 10, 27, 28],
        [11, 12, 29, 30]],

       [[13, 14, 31, 32],
        [15, 16, 33, 34],
        [17, 18, 35, 36]]])

In [213]:
np.r_[1, 2, 3]

array([1, 2, 3], dtype=int32)

In [214]:
np.r_[[1, 2, 3], 4, 5]

array([1, 2, 3, 4, 5])

In [215]:
np.r_[1:9, 98, 100]

array([  1,   2,   3,   4,   5,   6,   7,   8,  98, 100])

In [217]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [218]:
np.row_stack([np.array([1, 2, 3]), np.array([4, 5, 6])])

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
np.r_[[(1, 2, 3), (4, 5, 6)], [(7, 8, 9), (10, 11, 12)]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [226]:
np.c_[[(1, 2, 3), (4, 5, 6)], [(7, 8, 9), (10, 11, 12)]]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [227]:
np.r_[[(1, 2, 3), (4, 5, 6)], [(7, 8, 9)]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [252]:
np.r_[1:5].shape

(4,)

In [253]:
np.r_[1:5]

array([1, 2, 3, 4])

In [267]:
np.c_[1:5].shape

(4, 1)

In [268]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

In [269]:
np.c_[[1, 2, 3], [4, 5, 6]].shape

(3, 2)

In [270]:
np.c_[[1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [271]:
np.c_[[(1, 2, 3), (4, 5, 6)], [(7), (8)]]

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [272]:
a = np.arange(10)

In [273]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [276]:
np.hsplit(a, 3)

ValueError: array split does not result in an equal division

In [297]:
np.hsplit(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [298]:
for i in np.hsplit(a, 5):
    print(i)

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In [339]:
a.shape = 10, -1

In [340]:
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [341]:
np.vsplit(a, 2)

[array([[0],
        [1],
        [2],
        [3],
        [4]]),
 array([[5],
        [6],
        [7],
        [8],
        [9]])]

In [346]:
a = np.arange(12)

In [347]:
a.resize(2, 6)

In [348]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [349]:
np.hsplit(a, 2)

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [350]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [365]:
a = np.arange(18)

In [366]:
a.resize(3, 3, 2)

In [367]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [368]:
np.array_split(a, 2, axis=2)

[array([[[ 0],
         [ 2],
         [ 4]],
 
        [[ 6],
         [ 8],
         [10]],
 
        [[12],
         [14],
         [16]]]),
 array([[[ 1],
         [ 3],
         [ 5]],
 
        [[ 7],
         [ 9],
         [11]],
 
        [[13],
         [15],
         [17]]])]

In [370]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [371]:
np.array_split(a, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 array([[[12, 13],
         [14, 15],
         [16, 17]]])]

In [372]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [373]:
np.array_split(a, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 6,  7],
         [ 8,  9]],
 
        [[12, 13],
         [14, 15]]]),
 array([[[ 4,  5]],
 
        [[10, 11]],
 
        [[16, 17]]])]