In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a[2]

2

In [5]:
a[0]

0

In [7]:
a[-1]

11

In [8]:
a[-2]

10

In [9]:
a[12]

IndexError: index 12 is out of bounds for axis 0 with size 12

In [11]:
a[0] = 100

In [12]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [13]:
b = a[2:4]

In [14]:
b

array([2, 3])

In [15]:
b[0] = -100

In [16]:
b

array([-100,    3])

In [17]:
a

array([ 100,    1, -100,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [18]:
a[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
a[:5]

array([ 100,    1, -100,    3,    4])

In [22]:
a[-5:-1]

array([ 7,  8,  9, 10])

In [23]:
a[:]

array([ 100,    1, -100,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [27]:
a[1:6:2]

array([1, 3, 5])

In [30]:
a[::2]

array([ 100, -100,    4,    6,    8,   10])

In [35]:
a[::-1]

array([  11,   10,    9,    8,    7,    6,    5,    4,    3, -100,    1,
        100])

In [37]:
a[:4] = [-1, -2, -3, -4]

In [38]:
a

array([-1, -2, -3, -4,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a[4::2] = np.array([10, 20, 30, 40])

In [41]:
a

array([-1, -2, -3, -4, 10,  5, 20,  7, 30,  9, 40, 11])

In [57]:
for i in a:
    print(i, sep= ' ', end = ' ')

-1 -2 -3 -4 10 5 20 7 30 9 40 11 

In [3]:
x = np.array([(1, 2, 3), (10, 20, 30), (100, 200, 300)])

In [4]:
x

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [5]:
x[1, 1]

20

In [6]:
x[-1, -1]

300

In [7]:
x[0]

array([1, 2, 3])

In [8]:
x[1]

array([10, 20, 30])

In [9]:
x[2]

array([100, 200, 300])

In [10]:
x[0,:]

array([1, 2, 3])

In [11]:
x

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [16]:
x[:, 0]

array([  1,  10, 100])

In [28]:
x[:, 1]

array([  2,  20, 200])

In [29]:
x[:, 2]

array([  3,  30, 300])

In [33]:
for row in x:
    for val in row:
        print(val, end=' ')
    print()  

1 2 3 
10 20 30 
100 200 300 


In [37]:
for val in x.flat:
    print(val, end=' ')

1 2 3 10 20 30 100 200 300 

In [3]:
a = np.arange(1, 82).reshape(3, 3, 3, 3)

In [42]:
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]],


       [[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]],

        [[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]]]])

In [43]:
a[1, 2, 0, 1]

47

In [44]:
a[:, 1, :, :]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[64, 65, 66],
        [67, 68, 69],
        [70, 71, 72]]])

In [45]:
a[0, 0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a[0, 0, :, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a[:, :, 1, 1]

array([[ 5, 14, 23],
       [32, 41, 50],
       [59, 68, 77]])

In [8]:
a[0:2, 0:2, 1, 1]

array([[ 5, 14],
       [32, 41]])

In [18]:
a[..., 1, 1]

array([[ 5, 14, 23],
       [32, 41, 50],
       [59, 68, 77]])

In [5]:
a = np.arange(1, 9)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
a[0]

1

In [8]:
a[:3]

array([1, 2, 3])

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
a[0]

1

In [11]:
b = a[0]

In [12]:
b

1

In [13]:
b = a[[0]]

In [14]:
b

array([1])

In [15]:
b[0] = 100

In [16]:
b

array([100])

In [17]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a[[0, 1, 7, 5]]

array([1, 2, 8, 6])

In [19]:
b = a[[0, 1, 7, 5]]

In [20]:
b

array([1, 2, 8, 6])

In [21]:
b[0] = 100

In [22]:
b

array([100,   2,   8,   6])

In [23]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a[[0, 0, 1, 1, 1, 2, 3, 4, 5, 6, 7]]

array([1, 1, 2, 2, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a[[0, 1, 7, 5]] = [10, 20, 30, 40]

In [26]:
a

array([10, 20,  3,  4,  5, 40,  7, 30])

In [27]:
indx = [0, 0, 1, 1, 1, 2]

In [28]:
a[indx]

array([10, 10, 20, 20, 20,  3])

In [29]:
indx = np.array([0, 0, 1, 1, 1, 2])

In [30]:
indx

array([0, 0, 1, 1, 1, 2])

In [31]:
a[indx]

array([10, 10, 20, 20, 20,  3])

In [37]:
a

array([10, 20,  3,  4,  5, 40,  7, 30])

In [38]:
bIndx = [True, True, False, False, False, True, False, False]

In [39]:
a[bIndx]

array([10, 20, 40])

In [40]:
i = a > 5

In [41]:
i

array([ True,  True, False, False, False,  True,  True,  True])

In [42]:
a[i]

array([10, 20, 40,  7, 30])

In [43]:
a[a > 5]

array([10, 20, 40,  7, 30])

In [65]:
a = np.arange(1, 9)

In [66]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
i = np.array([[0, 1], [2,3]])

In [68]:
i

array([[0, 1],
       [2, 3]])

In [69]:
a[i]

array([[1, 2],
       [3, 4]])

In [70]:
i = [[0, 1], [2, 3]]

In [71]:
a[i]

array([[1, 2],
       [3, 4]])

In [72]:
a = np.arange(1, 13).reshape(3, 4)

In [73]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
indx = [2, 1, 0]

In [76]:
indx

[2, 1, 0]

In [77]:
a[indx]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [82]:
indx = np.array([[1, 0], [2, 1]])

In [83]:
indx

array([[1, 0],
       [2, 1]])

In [84]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
a[indx]

array([[[ 5,  6,  7,  8],
        [ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [92]:
indx.shape

(2, 2)

In [93]:
a.shape

(3, 4)

In [94]:
a[indx].shape

(2, 2, 4)

In [102]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
i0 = [0, 1]

In [104]:
i1 = [1, 2]

In [105]:
a[i0, i1]

array([2, 7])

In [106]:
a[:, i1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [107]:
a[i1, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
a[i0, 1]

array([2, 6])

In [111]:
a = np.arange(7)

In [112]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [113]:
a[[0, 4, 6]] = [-1, -2, -3]

In [114]:
a

array([-1,  1,  2,  3, -2,  5, -3])

In [116]:
a[[0, 0, 0, 1]] = [1, 2, 3, 100]

In [117]:
a

array([  3, 100,   2,   3,  -2,   5,  -3])

In [118]:
a[[0, 0, 0]] = a[[0, 0, 0]] +3

In [119]:
a

array([  6, 100,   2,   3,  -2,   5,  -3])

In [120]:
a[0] = a[0] + 3

In [121]:
a

array([  9, 100,   2,   3,  -2,   5,  -3])

In [122]:
a[[0, 0, 1, 2]] += 1

In [123]:
a

array([ 10, 101,   3,   3,  -2,   5,  -3])

In [125]:
a[[0, 1, 2]] += 1

In [126]:
a

array([ 11, 102,   4,   3,  -2,   5,  -3])