In [5]:
import numpy as np

In [2]:
lst = [1, 2, 3]

In [9]:
a = np.array([1, 2, 3])

In [6]:
lst * 2

[1, 2, 3, 1, 2, 3]

In [7]:
a * 2

array([2, 4, 6])

In [8]:
-a

array([-1, -2, -3])

In [9]:
a - 3

array([-2, -1,  0])

In [10]:
a + 2

array([3, 4, 5])

In [11]:
2 + a

array([3, 4, 5])

In [12]:
2 - a

array([ 1,  0, -1])

In [13]:
a * 5

array([ 5, 10, 15])

In [14]:
a / 5

array([0.2, 0.4, 0.6])

In [15]:
5 / a

array([5.        , 2.5       , 1.66666667])

In [16]:
a // 2

array([0, 1, 1], dtype=int32)

In [17]:
2 // a 

array([2, 1, 0], dtype=int32)

In [18]:
a ** 2

array([1, 4, 9])

In [19]:
a % 2

array([1, 0, 1], dtype=int32)

In [7]:
b = np.array([3, 4, 5])

In [10]:
a

array([1, 2, 3])

In [11]:
b

array([3, 4, 5])

In [12]:
a - b

array([-2, -2, -2])

In [13]:
a + b

array([4, 6, 8])

In [14]:
b + a

array([4, 6, 8])

In [15]:
a * b

array([ 3,  8, 15])

In [16]:
a / b

array([0.33333333, 0.5       , 0.6       ])

In [17]:
a // b

array([0, 0, 0])

In [18]:
a % b

array([1, 2, 3])

In [19]:
b ** a

array([  3,  16, 125])

In [21]:
a

array([1, 2, 3])

In [22]:
b

array([3, 4, 5])

In [23]:
b = np.array([3, 4, 5, 6])

In [24]:
a

array([1, 2, 3])

In [25]:
b

array([3, 4, 5, 6])

In [26]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [37]:
b = np.arange(1, 7)

In [38]:
b

array([1, 2, 3, 4, 5, 6])

In [39]:
b.resize(2, 3)

In [40]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a

array([1, 2, 3])

In [42]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [61]:
a = np.arange(1, 19)

In [62]:
a.resize(3, 3, 2)

In [63]:
b = np.ones((3, 2))

In [64]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [65]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
a - b

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]]])

In [67]:
a * 10

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]],

       [[130, 140],
        [150, 160],
        [170, 180]]])

In [68]:
a // b

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]])

In [70]:
a = np.array([1, 2, 6, 8])

In [71]:
a

array([1, 2, 6, 8])

In [72]:
a += 5

In [73]:
a

array([ 6,  7, 11, 13])

In [74]:
a + 5

array([11, 12, 16, 18])

In [75]:
a

array([ 6,  7, 11, 13])

In [76]:
a += 5

In [77]:
a

array([11, 12, 16, 18])

In [78]:
a -= 5

In [79]:
a

array([ 6,  7, 11, 13])

In [86]:
b = np.ones(4)

In [87]:
b

array([1., 1., 1., 1.])

In [88]:
a

array([ 6,  7, 11, 13])

In [89]:
b *= a

In [90]:
b

array([ 6.,  7., 11., 13.])

In [91]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [92]:
(a + b) * 5 -10

array([ 50.,  60., 100., 120.])