In [98]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 10, 20 ,30])

In [3]:
a

array([ 1,  2,  3, 10, 20, 30])

In [8]:
a > 5

array([False, False, False,  True,  True,  True])

In [9]:
a[a > 5]

array([10, 20, 30])

In [18]:
b = np.array([1, 2, 3, 4, 5, 6])

In [19]:
a

array([ 1,  2,  3, 10, 20, 30])

In [20]:
b

array([1, 2, 3, 4, 5, 6])

In [21]:
a == b

array([ True,  True,  True, False, False, False])

In [22]:
a != b

array([False, False, False,  True,  True,  True])

In [23]:
a != 2

array([ True, False,  True,  True,  True,  True])

In [27]:
a

array([ 1,  2,  3, 10, 20, 30])

In [28]:
b

array([1, 2, 3, 4, 5, 6])

In [31]:
np.greater(a, b)

array([False, False, False,  True,  True,  True])

In [32]:
a > b

array([False, False, False,  True,  True,  True])

In [33]:
np.less(a, b)

array([False, False, False, False, False, False])

In [34]:
a < b

array([False, False, False, False, False, False])

In [35]:
np.equal(a, b)

array([ True,  True,  True, False, False, False])

In [38]:
if a == b:
    print('a=b')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [51]:
if np.array_equal(a, b):
    print('a=b')

In [52]:
np.array_equal(a, b)

False

In [53]:
if not np.array_equal(a, b):
    print('a not equal b')

a not equal b


In [54]:
not np.array_equal(a, b)

True

In [55]:
a

array([ 1,  2,  3, 10, 20, 30])

In [56]:
np.any(a > 5)

True

In [58]:
np.any(a==3)

True

In [60]:
np.any(a==5)

False

In [61]:
a

array([ 1,  2,  3, 10, 20, 30])

In [62]:
b

array([1, 2, 3, 4, 5, 6])

In [63]:
np.any(a==b)

True

In [66]:
a==b

array([ True,  True,  True, False, False, False])

In [67]:
a

array([ 1,  2,  3, 10, 20, 30])

In [68]:
np.all(a > 5)

False

In [69]:
not np.all(a > 5)

True

In [70]:
np.all(a > 0)

True

In [72]:
a

array([ 1,  2,  3, 10, 20, 30])

In [73]:
b

array([1, 2, 3, 4, 5, 6])

In [74]:
np.all(a > b)

False

In [75]:
a

array([ 1,  2,  3, 10, 20, 30])

In [76]:
a / 0

C:\Users\dell\AppData\Local\Temp\ipykernel_19212\1979898162.py:1: RuntimeWarning: divide by zero encountered in divide
  a / 0


array([inf, inf, inf, inf, inf, inf])

In [82]:
b = np.array([1, 2, np.inf])

In [83]:
b

array([ 1.,  2., inf])

In [84]:
b * 0

C:\Users\dell\AppData\Local\Temp\ipykernel_19212\946493483.py:1: RuntimeWarning: invalid value encountered in multiply
  b * 0


array([ 0.,  0., nan])

In [86]:
c = b * 0

C:\Users\dell\AppData\Local\Temp\ipykernel_19212\171076696.py:1: RuntimeWarning: invalid value encountered in multiply
  c = b * 0


In [87]:
c

array([ 0.,  0., nan])

In [88]:
c.sum()

nan

In [89]:
a

array([ 1,  2,  3, 10, 20, 30])

In [90]:
a.sum()

66

In [99]:
b = np.array([1, 2, np.nan, np.inf, -np.inf])

In [100]:
b

array([  1.,   2.,  nan,  inf, -inf])

In [101]:
np.isinf(b)

array([False, False, False,  True,  True])

In [102]:
np.isnan(b)

array([False, False,  True, False, False])

In [121]:
indx = np.isinf(b)

In [122]:
indx

array([False, False, False,  True,  True])

In [123]:
b

array([  1.,   2.,  nan,  inf, -inf])

In [124]:
b[indx]

array([ inf, -inf])

In [125]:
b[~indx]

array([ 1.,  2., nan])

In [146]:
indx_2 = np.isnan(b)

In [147]:
indx_2

array([False, False,  True, False, False])

In [148]:
b

array([  1.,   2.,  nan,  inf, -inf])

In [149]:
b[~indx_2]

array([  1.,   2.,  inf, -inf])

In [153]:
np.isfinite(b)

array([ True,  True, False, False, False])

In [154]:
a = np.array([1 + 2.j, 3 - 4.j, 5])

In [155]:
a

array([1.+2.j, 3.-4.j, 5.+0.j])

In [156]:
np.iscomplex(a)

array([ True,  True, False])

In [157]:
np.isreal(a)

array([False, False,  True])

In [158]:
b

array([  1.,   2.,  nan,  inf, -inf])

In [159]:
np.isreal(b)

array([ True,  True,  True,  True,  True])

In [192]:
x = np.array([True, False, True, False])

In [193]:
y = np.array([True, True, False, False])

In [194]:
np.logical_and(x, y)

array([ True, False, False, False])

In [195]:
np.logical_or(x, y)

array([ True,  True,  True, False])

In [196]:
np.logical_not(x)

array([False,  True, False,  True])

In [197]:
np.logical_xor(x, y)

array([False,  True,  True, False])

In [198]:
a = np.array([1, 0, 2, 0])

In [199]:
b = np.array([3, 4, 0, 0])

In [200]:
np.logical_and(a, b)

array([ True, False, False, False])