In [11]:
import numpy as np

In [43]:
a = np.arange(1, 10).reshape(3, 3)

In [13]:
b = np.arange(10, 19)

In [14]:
b.resize(3, 3)

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [17]:
a * b

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [23]:
np.dot(a, b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [31]:
1*10 + 2*13 + 3*16, 1*11 + 2*14 + 3*17, 1*12 + 2*15 + 3* 18

(84, 90, 96)

In [34]:
4*10 + 5*13 + 6*16, 4*11 + 5*14 + 6*17, 4*12 + 5*15 + 6*18

(201, 216, 231)

In [37]:
7*10 + 8*13 + 9*16, 7*11 + 8*14 + 9*17, 7*12 + 8*15 + 9*18

(318, 342, 366)

In [38]:
np.dot(b, a)

array([[138, 171, 204],
       [174, 216, 258],
       [210, 261, 312]])

In [39]:
np.matmul(a ,b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [40]:
np.matmul(b , a)

array([[138, 171, 204],
       [174, 216, 258],
       [210, 261, 312]])

In [47]:
a.shape = -1, 1

In [48]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [49]:
np.dot(a, b)

ValueError: shapes (9,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [50]:
a.shape = 1, -1

In [51]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
np.dot(a, b)

ValueError: shapes (1,9) and (3,3) not aligned: 9 (dim 1) != 3 (dim 0)

In [54]:
a = np.arange(1, 10)

In [55]:
b = np.ones(9)

In [56]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
a * b

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
np.dot(a, b)

45.0

In [60]:
np.inner(a, b)

45.0

In [61]:
np.dot(b, a)

45.0

In [62]:
np.inner(b, a)

45.0

In [63]:
np.outer(a, b)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [64]:
np.outer(b, a)

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [65]:
a @ b

45.0

In [66]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
a.resize(3, 3)

In [70]:
b.resize(3, 3)

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
a @ b

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [74]:
np.dot(a, b)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [79]:
np.matmul(a, b)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [80]:
np.inner(a, b)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [81]:
np.outer(a, b)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [82]:
b @ a

array([[12., 15., 18.],
       [12., 15., 18.],
       [12., 15., 18.]])

In [83]:
np.dot(b, a)

array([[12., 15., 18.],
       [12., 15., 18.],
       [12., 15., 18.]])

In [84]:
np.matmul(b, a)

array([[12., 15., 18.],
       [12., 15., 18.],
       [12., 15., 18.]])

In [86]:
np.inner(b, a)

array([[ 6., 15., 24.],
       [ 6., 15., 24.],
       [ 6., 15., 24.]])

In [87]:
np.outer(b, a)

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [94]:
a = np.array([1, 2, 3])

In [95]:
b = np.arange(4, 10).reshape(3, 2)

In [96]:
a

array([1, 2, 3])

In [97]:
b

array([[4, 5],
       [6, 7],
       [8, 9]])

In [99]:
a @ b

array([40, 46])

In [100]:
np.dot(a, b)

array([40, 46])

In [101]:
np.dot(b, a)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [102]:
a = np.array([1, 2])

In [103]:
b

array([[4, 5],
       [6, 7],
       [8, 9]])

In [104]:
a

array([1, 2])

In [105]:
np.dot(b, a)

array([14, 20, 26])

In [106]:
np.dot(a, b)

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [107]:
a

array([1, 2])

In [108]:
b

array([[4, 5],
       [6, 7],
       [8, 9]])

In [111]:
a.shape = -1, 1

In [112]:
a

array([[1],
       [2]])

In [113]:
np.dot(b, a)

array([[14],
       [20],
       [26]])

In [115]:
b @ a

array([[14],
       [20],
       [26]])

In [116]:
a = np.array([[1, 2, 3], [1, 4, 9], [1, 8 , 27]])

In [117]:
a

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [138]:
np.linalg.matrix_rank(a)

3

In [139]:
a

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [140]:
y = np.array([10, 20, 30])

In [141]:
y

array([10, 20, 30])

In [143]:
np.linalg.solve(a, y)

array([-5.        , 10.        , -1.66666667])

In [144]:
a

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [145]:
invA = np.linalg.inv(a)

In [147]:
invA

array([[ 3.        , -2.5       ,  0.5       ],
       [-1.5       ,  2.        , -0.5       ],
       [ 0.33333333, -0.5       ,  0.16666667]])

In [149]:
invA @ y

array([-5.        , 10.        , -1.66666667])