In [12]:
import numpy as np

In [13]:
a = np.array([1, 2, 3, 4, 4, 3, 2, 1])

In [14]:
a

array([1, 2, 3, 4, 4, 3, 2, 1])

In [15]:
b = set(a)

In [16]:
b = list(b)

In [17]:
np.array(b)

array([1, 2, 3, 4])

In [18]:
a = np.array([1, 2, 3, 4, 4, 3, 2, 1])

In [19]:
a

array([1, 2, 3, 4, 4, 3, 2, 1])

In [20]:
setA = np.unique(a)

In [21]:
setA

array([1, 2, 3, 4])

In [23]:
np.unique(a, return_counts = True)

(array([1, 2, 3, 4]), array([2, 2, 2, 2], dtype=int64))

In [24]:
b = np.array([1, 2, 2, 3, 3, 3, 4])

In [26]:
np.unique(b, return_counts=True)

(array([1, 2, 3, 4]), array([1, 2, 3, 1], dtype=int64))

In [28]:
a

array([1, 2, 3, 4, 4, 3, 2, 1])

In [29]:
np.unique(a, return_index=True)

(array([1, 2, 3, 4]), array([0, 1, 2, 3], dtype=int64))

In [30]:
np.unique(a, return_inverse=True)

(array([1, 2, 3, 4]), array([0, 1, 2, 3, 3, 2, 1, 0], dtype=int64))

In [33]:
setA, indx = np.unique(a, return_inverse=True)

In [34]:
setA

array([1, 2, 3, 4])

In [35]:
indx

array([0, 1, 2, 3, 3, 2, 1, 0], dtype=int64)

In [38]:
setA[indx]

array([1, 2, 3, 4, 4, 3, 2, 1])

In [91]:
x = np.array([[0, 1, 1, 2], [0, 1, 1, 2], [9, 1, 1, 2]])

In [92]:
x

array([[0, 1, 1, 2],
       [0, 1, 1, 2],
       [9, 1, 1, 2]])

In [93]:
np.unique(x)

array([0, 1, 2, 9])

In [94]:
np.unique(x, axis=0)

array([[0, 1, 1, 2],
       [9, 1, 1, 2]])

In [95]:
np.unique(x, axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [9, 1, 2]])

In [96]:
np.unique(x, axis=1).shape

(3, 3)

In [97]:
x.shape

(3, 4)

In [122]:
x = np.array([0, 1, 2, 3])

In [123]:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [124]:
x

array([0, 1, 2, 3])

In [125]:
y

array([1, 2, 3, 4, 5, 6, 7, 8])

In [126]:
np.in1d(x, y)

array([False,  True,  True,  True])

In [128]:
np.random.shuffle(y)

In [129]:
y

array([2, 5, 6, 3, 4, 7, 1, 8])

In [130]:
np.in1d(x, y)

array([False,  True,  True,  True])

In [131]:
x

array([0, 1, 2, 3])

In [132]:
y

array([2, 5, 6, 3, 4, 7, 1, 8])

In [133]:
np.intersect1d(x, y)

array([1, 2, 3])

In [134]:
np.union1d(x, y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [135]:
np.setdiff1d(x, y)

array([0])

In [136]:
np.setdiff1d(y, x)

array([4, 5, 6, 7, 8])

In [137]:
np.setxor1d(x, y)

array([0, 4, 5, 6, 7, 8])

In [138]:
np.setxor1d(y, x)

array([0, 4, 5, 6, 7, 8])