In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 10, 20, 30])

In [3]:
b = np.array([2])

In [4]:
a

array([ 1,  2,  3, 10, 20, 30])

In [5]:
b

array([2])

In [6]:
a * b

array([ 2,  4,  6, 20, 40, 60])

In [7]:
b * a

array([ 2,  4,  6, 20, 40, 60])

In [10]:
a + b

array([ 3,  4,  5, 12, 22, 32])

In [24]:
b = np.array([2, 2])

In [25]:
a

array([ 1,  2,  3, 10, 20, 30])

In [26]:
b

array([2, 2])

In [27]:
a * b

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

In [28]:
a + b 

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

In [29]:
a.ndim

1

In [30]:
b.ndim

1

In [49]:
a = np.arange(1, 10).reshape(3, 3)

In [50]:
b = np.array([4, 5, 6])

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
b

array([4, 5, 6])

In [54]:
a * b

array([[ 4, 10, 18],
       [16, 25, 36],
       [28, 40, 54]])

In [55]:
b * a

array([[ 4, 10, 18],
       [16, 25, 36],
       [28, 40, 54]])

In [56]:
a + b

array([[ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [57]:
b + a

array([[ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [98]:
a = np.arange(6).reshape(3, 1, 2)

In [99]:
b = np.ones(4).reshape(2, 2)

In [100]:
a

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [101]:
b

array([[1., 1.],
       [1., 1.]])

In [102]:
c = a * b

In [103]:
c

array([[[0., 1.],
        [0., 1.]],

       [[2., 3.],
        [2., 3.]],

       [[4., 5.],
        [4., 5.]]])

In [104]:
c.shape

(3, 2, 2)

In [105]:
d = a + b

In [106]:
d

array([[[1., 2.],
        [1., 2.]],

       [[3., 4.],
        [3., 4.]],

       [[5., 6.],
        [5., 6.]]])

In [107]:
d.shape

(3, 2, 2)

In [108]:
# a: 3 x 1 x 2
# b:     2 x 2

# a:  3  x (2) x 2
# b: (1) x  2  x 2

In [109]:
a

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [110]:
b

array([[1., 1.],
       [1., 1.]])

In [111]:
a = a.reshape(2, 3, 1)

In [112]:
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [113]:
b

array([[1., 1.],
       [1., 1.]])

In [118]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3,1) (2,2) 

In [119]:
# a: 2 x 3 x 1
# b:     2 x 2

# a:  2  x 3 x 1
# b: (1) x 2 x 2

In [120]:
b = np.ones(6).reshape(3, 2)

In [121]:
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [122]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [123]:
c = a * b

In [124]:
c

array([[[0., 0.],
        [1., 1.],
        [2., 2.]],

       [[3., 3.],
        [4., 4.],
        [5., 5.]]])

In [128]:
c.shape

(2, 3, 2)

In [ ]:
# a: 2 x 3 x 1
# b:     3 x 2

# a:  2  x 3 x (1)
# b: (1) x 3 x  2

In [239]:
a = np.array([1, 2, 3])

In [240]:
b = np.array([4, 5])

In [241]:
c = np.array([6, 7, 8, 9])

In [243]:
a * b + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [244]:
# a:  1 x 1 x 3
# b:  1 x 2 x 1
# b:  4 x 1 x 1

In [245]:
a.shape = 1, 1, -1

In [246]:
b.shape = 1, -1, 1

In [247]:
c.shape = -1, 1, 1

In [251]:
a

array([[[1, 2, 3]]])

In [252]:
b

array([[[4],
        [5]]])

In [253]:
c

array([[[6]],

       [[7]],

       [[8]],

       [[9]]])

In [254]:
c = a * b + c

In [255]:
c

array([[[10, 14, 18],
        [11, 16, 21]],

       [[11, 15, 19],
        [12, 17, 22]],

       [[12, 16, 20],
        [13, 18, 23]],

       [[13, 17, 21],
        [14, 19, 24]]])

In [258]:
c.shape

(4, 2, 3)

In [259]:
a = np.array([1, 2, 3])

In [260]:
b = np.array([4, 5])

In [261]:
c = np.array([6, 7, 8, 9])

In [263]:
an, bn, cn, = np.ix_(a, b, c)

In [264]:
an.shape

(3, 1, 1)

In [265]:
bn.shape

(1, 2, 1)

In [266]:
cn.shape

(1, 1, 4)

In [267]:
an

array([[[1]],

       [[2]],

       [[3]]])

In [268]:
bn

array([[[4],
        [5]]])

In [269]:
cn

array([[[6, 7, 8, 9]]])

In [270]:
c = an * bn + cn

In [271]:
c

array([[[10, 11, 12, 13],
        [11, 12, 13, 14]],

       [[14, 15, 16, 17],
        [16, 17, 18, 19]],

       [[18, 19, 20, 21],
        [21, 22, 23, 24]]])