In [58]:
import numpy as np

In [59]:
a = np.array([1, 2, 3, 10, 20 ,30])

In [60]:
a.resize(3, 2)

In [61]:
a

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [62]:
a.sum(axis=0)

array([24, 42])

In [63]:
np.amax(a, axis=0)

array([20, 30])

In [64]:
np.sum(a, axis=1)

array([ 3, 13, 50])

In [65]:
np.amax(a, axis=1)

array([ 2, 10, 30])

In [67]:
np.unique(a, axis=0)

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [98]:
b = np.array([1, 1, 1, 1, 1, 1])

In [99]:
b.resize(3, 2)

In [100]:
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [101]:
np.unique(b, axis=1)

array([[1],
       [1],
       [1]])